const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9K4NFZ9-De4GF2yxhsbbRbaCv3wW1_0qYlQ&usqp=CAU',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9k1fj_8Kv9yd5AHlKkDcXfKtrMgdOJp_0Jw&usqp=CAU',
            price: 80,
            brand: 'Adidas',
            rating: 5.0,
            numReviews: 7,
            countInStock: 10,
            description: 'A fit shirt',
        },
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9K4NFZ9-De4GF2yxhsbbRbaCv3wW1_0qYlQ&usqp=CAU',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9k1fj_8Kv9yd5AHlKkDcXfKtrMgdOJp_0Jw&usqp=CAU',
            price: 80,
            brand: 'Adidas',
            rating: 5.0,
            numReviews: 7,
            countInStock: 10,
            description: 'A fit shirt',
        },
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9K4NFZ9-De4GF2yxhsbbRbaCv3wW1_0qYlQ&usqp=CAU',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9k1fj_8Kv9yd5AHlKkDcXfKtrMgdOJp_0Jw&usqp=CAU',
            price: 80,
            brand: 'Adidas',
            rating: 5.0,
            numReviews: 7,
            countInStock: 10,
            description: 'A fit shirt',
        },
    ],
}

export default data;